#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef D1CORE_SWIFT_H
#define D1CORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Security;
@import os.log;
#endif

#import <D1Core/D1Core.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="D1Core",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSMutableData;

SWIFT_CLASS("_TtC6D1Core17A2InMemoryStorage")
@interface A2InMemoryStorage : NSObject
+ (BOOL)addAuthorizationToken:(NSMutableData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
+ (BOOL)deleteAuthorizationTokensAndReturnError:(NSError * _Nullable * _Nullable)error;
+ (NSArray<NSMutableData *> * _Nullable)authorizationTokensAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSData;

SWIFT_CLASS("_TtC6D1Core13SqliteStorage")
@interface SqliteStorage : NSObject
@property (nonatomic, copy) NSString * _Nullable dbPath;
/// init information.
/// Create file based on provided name.
/// File location based on appGroupId
/// \param name db file identifier
///
/// \param appGroupId nil will set file location to libraryDirectory.
///
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (NSMutableData * _Nullable)readDataWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)writeDataWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (BOOL)openAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)closeAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)deleteKeyWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (void)deleteStorage;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class KdfFeedbackCipher;

SWIFT_CLASS("_TtC6D1Core22EncryptedSqliteStorage")
@interface EncryptedSqliteStorage : SqliteStorage
@property (nonatomic, strong) KdfFeedbackCipher * _Nullable cipher;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (BOOL)writeDataWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)readDataWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteKeyWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (void)wipe;
- (NSMutableData * _Nullable)generateKekIvAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)getKekIvAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6D1Core9A2Storage")
@interface A2Storage : EncryptedSqliteStorage
- (nullable instancetype)initWithAppGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setAuthTokenWithToken:(NSMutableData * _Nonnull)token error:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)getAuthTokenAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteAuthTokenAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setRefreshTokenWithToken:(NSMutableData * _Nonnull)token error:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)getRefreshTokenAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteRefreshTokenAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end

@class RandomUtil;

SWIFT_CLASS("_TtC6D1Core12AesGcmCipher")
@interface AesGcmCipher : NSObject
@property (nonatomic, strong) RandomUtil * _Nonnull randomUtil;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ivSize;)
+ (NSInteger)ivSize SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagSize;)
+ (NSInteger)tagSize SWIFT_WARN_UNUSED_RESULT;
- (void)setRandom:(RandomUtil * _Nonnull)ran;
- (NSMutableData * _Nullable)tpyrcneWithPlaintext:(NSData * _Nonnull)plaintext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)tpyrcedWithCiphertext:(NSData * _Nonnull)ciphertext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)wipe;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core12AuthnStorage")
@interface AuthnStorage : EncryptedSqliteStorage
- (nullable instancetype)initAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setMsUrlWithData:(NSString * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getMsUrl SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteMsUrlAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTenantIdWithData:(NSString * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getTenantId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteTenantIdAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core10Base64Util")
@interface Base64Util : NSObject
+ (NSString * _Nonnull)base64UrlEncodedString:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum CardOperation : NSInteger;

SWIFT_CLASS("_TtC6D1Core16CardEnumCaaSUtil")
@interface CardEnumCaaSUtil : NSObject
+ (D1COngoingOperation)stringToOngoingOperation:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CStateReason)stringToStateReason:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)cardOperationToString:(enum CardOperation)cardOperation SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core12CardEnumUtil")
@interface CardEnumUtil : NSObject
+ (D1CAssetContentType)stringToAssetContentType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardState)stringToCardState:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardScheme)stringToCardScheme:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardMimeType)stringToCardMimeType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)cardActionToString:(D1CCardAction)cardAction SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)walletTypeToString:(D1CWalletType)walletType SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)stateReasonToString:(D1CStateReason)stateReason SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CardOperation, closed) {
  CardOperationResume = 0,
  CardOperationSuspend = 1,
  CardOperationReplace = 2,
};


SWIFT_CLASS("_TtC6D1Core23CardPushDetailsEnumUtil")
@interface CardPushDetailsEnumUtil : NSObject
+ (D1CAssetContentType)stringToAssetContentType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)contextToString:(D1CCardPushDetailsContext)context SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core16CardSettingsUtil")
@interface CardSettingsUtil : NSObject
+ (D1CCardSettingsPeriodType)stringToPeriodType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)periodTypeToString:(D1CCardSettingsPeriodType)periodType SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardSettingsGeographyRegion)stringToGeographyRegion:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)geographyRegionToString:(D1CCardSettingsGeographyRegion)geographyRegion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLSessionTask;
@class NSHTTPURLResponse;
@class NSURLRequest;

SWIFT_PROTOCOL("_TtP6D1Core22SessionManagerDelegate_")
@protocol SessionManagerDelegate <NSObject>
@optional
- (void)customUrlSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC6D1Core10URLNetwork")
@interface URLNetwork : NSOperation <SessionManagerDelegate>
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
@property (nonatomic, readonly, getter=isExecuting) BOOL executing;
@property (nonatomic, readonly, getter=isFinished) BOOL finished;
- (void)main;
- (void)start;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6D1Core26CardTransactionListNetwork")
@interface CardTransactionListNetwork : URLNetwork
@end


SWIFT_CLASS("_TtC6D1Core11CoreStorage")
@interface CoreStorage : EncryptedSqliteStorage
- (nullable instancetype)initAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)generateAppInstanceIDAndReturnError:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)appInstanceID SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteAppInstanceIDAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


@interface D1CAuthn (SWIFT_EXTENSION(D1Core))
- (void)unenrollAuthnCredentialsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


@class D1LogMessage;

SWIFT_CLASS("_TtC6D1Core5D1Log")
@interface D1Log : NSObject
+ (void)logMessage:(D1LogMessage * _Nonnull)message level:(os_log_type_t)level;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LogSubsystem : NSInteger;

SWIFT_CLASS("_TtC6D1Core12D1LogMessage")
@interface D1LogMessage : NSObject
- (nonnull instancetype)initWithMessageString:(NSString * _Nullable)messageString sensitivePrefix:(NSString * _Nullable)sensitivePrefix sensitiveString:(NSString * _Nullable)sensitiveString file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function subsystem:(enum LogSubsystem)subsystem OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6D1Core29EnrollAuthnCredentialsNetwork")
@interface EnrollAuthnCredentialsNetwork : URLNetwork
@end

@class NSFileManager;
@class NSURL;

SWIFT_CLASS("_TtC6D1Core11FileStorage")
@interface FileStorage : NSObject
@property (nonatomic, readonly, strong) NSFileManager * _Nonnull fileManager;
- (nonnull instancetype)init;
- (nonnull instancetype)init:(NSFileManager * _Nonnull)fileManager folder:(NSString * _Nullable)folder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)write:(NSData * _Nonnull)data fileName:(NSString * _Nonnull)fileName error:(NSError * _Nullable * _Nullable)error;
- (NSData * _Nullable)dataFileName:(NSString * _Nonnull)fileName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)getDataFromFileNameContaining:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSURL *> * _Nullable)filesAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteFilesAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


SWIFT_CLASS("_TtC6D1Core8HashUtil")
@interface HashUtil : NSObject
+ (NSMutableData * _Nonnull)hashDataForData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)hashStringFromString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core7HexUtil")
@interface HexUtil : NSObject
+ (NSMutableData * _Nonnull)dataForHexStr:(NSString * _Nonnull)hex SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)hexStringFromData:(NSMutableData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core20InMemoryArrayStorage")
@interface InMemoryArrayStorage : NSObject
+ (NSArray<NSMutableData *> * _Nullable)readArrayWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)writeInArrayWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
+ (BOOL)deleteWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core15InMemoryStorage")
@interface InMemoryStorage : NSObject
+ (NSMutableData * _Nullable)readDataWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)writeWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
+ (BOOL)deleteWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LAContext;

SWIFT_CLASS("_TtC6D1Core17KdfFeedbackCipher")
@interface KdfFeedbackCipher : NSObject
@property (nonatomic, copy) NSString * _Nonnull appGroupId;
@property (nonatomic) BOOL useDefaultAppGroupId;
@property (nonatomic, strong) NSMutableData * _Nullable kekIv;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull salt;)
+ (NSString * _Nonnull)salt SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull keyAlias;)
+ (NSString * _Nonnull)keyAlias SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kekKeyAlias;)
+ (NSString * _Nonnull)kekKeyAlias SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull label;)
+ (NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable sAppID;)
+ (NSString * _Nullable)sAppID SWIFT_WARN_UNUSED_RESULT;
+ (void)setSAppID:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger length;)
+ (NSInteger)length SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSNumber *> * _Nonnull blank;)
+ (NSArray<NSNumber *> * _Nonnull)blank SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithAppGroupId:(NSString * _Nonnull)appGroupId OBJC_DESIGNATED_INITIALIZER;
- (NSMutableData * _Nonnull)fixedInputData SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)tpyrcneWithPlaintext:(NSData * _Nonnull)plaintext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)tpyrcedWithCiphertext:(NSData * _Nonnull)ciphertext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)wipe;
- (void)reset;
- (SecKeyRef _Nullable)generateKskKeyPairAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (LAContext * _Nullable)generateContextAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDwp SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)applicationID SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6D1Core21KdfFeedbackHmacSha256")
@interface KdfFeedbackHmacSha256 : NSObject
@property (nonatomic) uint32_t keyLength;
@property (nonatomic, strong) NSMutableData * _Nonnull keyInput;
@property (nonatomic, strong) NSMutableData * _Nonnull iv;
@property (nonatomic, strong) NSMutableData * _Nonnull fixedInputData;
- (nonnull instancetype)initWithLength:(uint32_t)length input:(NSMutableData * _Nonnull)input iv:(NSMutableData * _Nonnull)iv fixedInputData:(NSMutableData * _Nonnull)fixedInputData OBJC_DESIGNATED_INITIALIZER;
- (NSMutableData * _Nullable)deriveAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)wipe;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, LogSubsystem, open) {
  LogSubsystemD1core = 0x00,
  LogSubsystemD1sdk = 0x01,
  LogSubsystemUnidentify = 0xFF,
};


SWIFT_CLASS("_TtC6D1Core6Memory")
@interface Memory : NSObject
+ (BOOL)validate:(NSMutableData * _Nonnull)data length:(NSInteger)length SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)memcmpWithData:(NSMutableData * _Nonnull)data otherData:(NSMutableData * _Nonnull)otherData length:(NSInteger)length SWIFT_WARN_UNUSED_RESULT;
+ (void)revxor:(NSMutableData * _Nonnull)dst src:(NSData * _Nonnull)src msk:(NSData * _Nonnull)msk;
+ (void)xor:(NSMutableData * _Nonnull)dst src:(NSMutableData * _Nonnull)src msk:(NSMutableData * _Nonnull)msk;
+ (void)shouldChangeCharactersInRangeWithCurrentMask:(NSMutableData * _Nonnull)currentMask currentInputValueMasked:(NSMutableData * _Nonnull)currentInputValueMasked tempMask:(NSMutableData * _Nonnull)tempMask nextInputValueMasked:(NSMutableData * _Nonnull)nextInputValueMasked newInputLength:(NSInteger)newInputLength rangeLoc:(NSInteger)rangeLoc rangeLen:(NSInteger)rangeLen stringLength:(NSInteger)stringLength fixedByteLength:(NSInteger)fixedByteLength subCharSequenceToChangeAfterChange:(NSMutableData * _Nonnull)subCharSequenceToChangeAfterChange;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core17MessagingEnumUtil")
@interface MessagingEnumUtil : NSObject
+ (D1CMessageType)messageTypeForString:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CMessageFormat)messageFormatForString:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core16MessagingStorage")
@interface MessagingStorage : EncryptedSqliteStorage
- (nullable instancetype)initWithConsumerId:(NSString * _Nullable)consumerId issuerId:(NSString * _Nullable)issuerId error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setShouldTryAfterLogin:(BOOL)tryUpdate error:(NSError * _Nullable * _Nullable)error;
- (BOOL)getShouldTryAfterLogin SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setIsRegistered:(BOOL)tokenRegistered error:(NSError * _Nullable * _Nullable)error;
- (BOOL)getIsRegistered SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core17NetworkMonitoring")
@interface NetworkMonitoring : NSObject
@property (nonatomic) BOOL isNetworkAvailable;
@property (nonatomic, readonly) BOOL isMonitoring;
@property (nonatomic, copy) void (^ _Nullable onUpdateNetworkStatus)(BOOL);
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NetworkMonitoring * _Nonnull shared;)
+ (NetworkMonitoring * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)startMonitoring;
- (void)stopMonitoring;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6D1Core33NotifyEnrollmentCompletionNetwork")
@interface NotifyEnrollmentCompletionNetwork : URLNetwork
@end


SWIFT_CLASS("_TtC6D1Core11PushStorage")
@interface PushStorage : EncryptedSqliteStorage
- (nullable instancetype)initAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setPushToken:(NSString * _Nonnull)token error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getPushToken SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core10RandomUtil")
@interface RandomUtil : NSObject
- (NSMutableData * _Nullable)randomDataWithCount:(NSInteger)count error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLAuthenticationChallenge;
@class NSURLCredential;

SWIFT_CLASS("_TtC6D1Core14SessionManager")
@interface SessionManager : NSObject <NSURLSessionTaskDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SessionManager * _Nonnull shared;)
+ (SessionManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <SessionManagerDelegate> _Nullable delegate;
@property (nonatomic, strong) NSURLSession * _Nullable session;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
@end






SWIFT_CLASS("_TtC6D1Core31UnenrollAuthnCredentialsNetwork")
@interface UnenrollAuthnCredentialsNetwork : URLNetwork
@end


SWIFT_CLASS("_TtC6D1Core5Wiper")
@interface Wiper : NSObject
+ (void)wipeBytes:(void const * _Nonnull)data length:(NSInteger)length;
+ (void)wipeData:(NSMutableData * _Nullable)data;
+ (void)wipeDataArray:(NSArray<NSData *> * _Nonnull)dataArray;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef D1CORE_SWIFT_H
#define D1CORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Security;
@import os.log;
#endif

#import <D1Core/D1Core.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="D1Core",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSMutableData;

SWIFT_CLASS("_TtC6D1Core17A2InMemoryStorage")
@interface A2InMemoryStorage : NSObject
+ (BOOL)addAuthorizationToken:(NSMutableData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
+ (BOOL)deleteAuthorizationTokensAndReturnError:(NSError * _Nullable * _Nullable)error;
+ (NSArray<NSMutableData *> * _Nullable)authorizationTokensAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSData;

SWIFT_CLASS("_TtC6D1Core13SqliteStorage")
@interface SqliteStorage : NSObject
@property (nonatomic, copy) NSString * _Nullable dbPath;
/// init information.
/// Create file based on provided name.
/// File location based on appGroupId
/// \param name db file identifier
///
/// \param appGroupId nil will set file location to libraryDirectory.
///
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (NSMutableData * _Nullable)readDataWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)writeDataWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (BOOL)openAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)closeAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)deleteKeyWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (void)deleteStorage;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class KdfFeedbackCipher;

SWIFT_CLASS("_TtC6D1Core22EncryptedSqliteStorage")
@interface EncryptedSqliteStorage : SqliteStorage
@property (nonatomic, strong) KdfFeedbackCipher * _Nullable cipher;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (BOOL)writeDataWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)readDataWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteKeyWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (void)wipe;
- (NSMutableData * _Nullable)generateKekIvAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)getKekIvAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6D1Core9A2Storage")
@interface A2Storage : EncryptedSqliteStorage
- (nullable instancetype)initWithAppGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setAuthTokenWithToken:(NSMutableData * _Nonnull)token error:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)getAuthTokenAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteAuthTokenAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setRefreshTokenWithToken:(NSMutableData * _Nonnull)token error:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)getRefreshTokenAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteRefreshTokenAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end

@class RandomUtil;

SWIFT_CLASS("_TtC6D1Core12AesGcmCipher")
@interface AesGcmCipher : NSObject
@property (nonatomic, strong) RandomUtil * _Nonnull randomUtil;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ivSize;)
+ (NSInteger)ivSize SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tagSize;)
+ (NSInteger)tagSize SWIFT_WARN_UNUSED_RESULT;
- (void)setRandom:(RandomUtil * _Nonnull)ran;
- (NSMutableData * _Nullable)tpyrcneWithPlaintext:(NSData * _Nonnull)plaintext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)tpyrcedWithCiphertext:(NSData * _Nonnull)ciphertext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)wipe;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core12AuthnStorage")
@interface AuthnStorage : EncryptedSqliteStorage
- (nullable instancetype)initAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setMsUrlWithData:(NSString * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getMsUrl SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteMsUrlAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTenantIdWithData:(NSString * _Nonnull)data error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getTenantId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteTenantIdAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core10Base64Util")
@interface Base64Util : NSObject
+ (NSString * _Nonnull)base64UrlEncodedString:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum CardOperation : NSInteger;

SWIFT_CLASS("_TtC6D1Core16CardEnumCaaSUtil")
@interface CardEnumCaaSUtil : NSObject
+ (D1COngoingOperation)stringToOngoingOperation:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CStateReason)stringToStateReason:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)cardOperationToString:(enum CardOperation)cardOperation SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core12CardEnumUtil")
@interface CardEnumUtil : NSObject
+ (D1CAssetContentType)stringToAssetContentType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardState)stringToCardState:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardScheme)stringToCardScheme:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardMimeType)stringToCardMimeType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)cardActionToString:(D1CCardAction)cardAction SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)walletTypeToString:(D1CWalletType)walletType SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)stateReasonToString:(D1CStateReason)stateReason SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CardOperation, closed) {
  CardOperationResume = 0,
  CardOperationSuspend = 1,
  CardOperationReplace = 2,
};


SWIFT_CLASS("_TtC6D1Core23CardPushDetailsEnumUtil")
@interface CardPushDetailsEnumUtil : NSObject
+ (D1CAssetContentType)stringToAssetContentType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)contextToString:(D1CCardPushDetailsContext)context SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core16CardSettingsUtil")
@interface CardSettingsUtil : NSObject
+ (D1CCardSettingsPeriodType)stringToPeriodType:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)periodTypeToString:(D1CCardSettingsPeriodType)periodType SWIFT_WARN_UNUSED_RESULT;
+ (D1CCardSettingsGeographyRegion)stringToGeographyRegion:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)geographyRegionToString:(D1CCardSettingsGeographyRegion)geographyRegion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLSessionTask;
@class NSHTTPURLResponse;
@class NSURLRequest;

SWIFT_PROTOCOL("_TtP6D1Core22SessionManagerDelegate_")
@protocol SessionManagerDelegate <NSObject>
@optional
- (void)customUrlSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC6D1Core10URLNetwork")
@interface URLNetwork : NSOperation <SessionManagerDelegate>
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
@property (nonatomic, readonly, getter=isExecuting) BOOL executing;
@property (nonatomic, readonly, getter=isFinished) BOOL finished;
- (void)main;
- (void)start;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6D1Core26CardTransactionListNetwork")
@interface CardTransactionListNetwork : URLNetwork
@end


SWIFT_CLASS("_TtC6D1Core11CoreStorage")
@interface CoreStorage : EncryptedSqliteStorage
- (nullable instancetype)initAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)generateAppInstanceIDAndReturnError:(NSError * _Nullable * _Nullable)error;
- (NSMutableData * _Nullable)appInstanceID SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteAppInstanceIDAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


@interface D1CAuthn (SWIFT_EXTENSION(D1Core))
- (void)unenrollAuthnCredentialsWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


@class D1LogMessage;

SWIFT_CLASS("_TtC6D1Core5D1Log")
@interface D1Log : NSObject
+ (void)logMessage:(D1LogMessage * _Nonnull)message level:(os_log_type_t)level;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LogSubsystem : NSInteger;

SWIFT_CLASS("_TtC6D1Core12D1LogMessage")
@interface D1LogMessage : NSObject
- (nonnull instancetype)initWithMessageString:(NSString * _Nullable)messageString sensitivePrefix:(NSString * _Nullable)sensitivePrefix sensitiveString:(NSString * _Nullable)sensitiveString file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function subsystem:(enum LogSubsystem)subsystem OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6D1Core29EnrollAuthnCredentialsNetwork")
@interface EnrollAuthnCredentialsNetwork : URLNetwork
@end

@class NSFileManager;
@class NSURL;

SWIFT_CLASS("_TtC6D1Core11FileStorage")
@interface FileStorage : NSObject
@property (nonatomic, readonly, strong) NSFileManager * _Nonnull fileManager;
- (nonnull instancetype)init;
- (nonnull instancetype)init:(NSFileManager * _Nonnull)fileManager folder:(NSString * _Nullable)folder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)write:(NSData * _Nonnull)data fileName:(NSString * _Nonnull)fileName error:(NSError * _Nullable * _Nullable)error;
- (NSData * _Nullable)dataFileName:(NSString * _Nonnull)fileName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)getDataFromFileNameContaining:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSURL *> * _Nullable)filesAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteFilesAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


SWIFT_CLASS("_TtC6D1Core8HashUtil")
@interface HashUtil : NSObject
+ (NSMutableData * _Nonnull)hashDataForData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)hashStringFromString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core7HexUtil")
@interface HexUtil : NSObject
+ (NSMutableData * _Nonnull)dataForHexStr:(NSString * _Nonnull)hex SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)hexStringFromData:(NSMutableData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core20InMemoryArrayStorage")
@interface InMemoryArrayStorage : NSObject
+ (NSArray<NSMutableData *> * _Nullable)readArrayWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)writeInArrayWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
+ (BOOL)deleteWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core15InMemoryStorage")
@interface InMemoryStorage : NSObject
+ (NSMutableData * _Nullable)readDataWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)writeWithData:(NSData * _Nonnull)data key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
+ (BOOL)deleteWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LAContext;

SWIFT_CLASS("_TtC6D1Core17KdfFeedbackCipher")
@interface KdfFeedbackCipher : NSObject
@property (nonatomic, copy) NSString * _Nonnull appGroupId;
@property (nonatomic) BOOL useDefaultAppGroupId;
@property (nonatomic, strong) NSMutableData * _Nullable kekIv;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull salt;)
+ (NSString * _Nonnull)salt SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull keyAlias;)
+ (NSString * _Nonnull)keyAlias SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kekKeyAlias;)
+ (NSString * _Nonnull)kekKeyAlias SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull label;)
+ (NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable sAppID;)
+ (NSString * _Nullable)sAppID SWIFT_WARN_UNUSED_RESULT;
+ (void)setSAppID:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger length;)
+ (NSInteger)length SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSNumber *> * _Nonnull blank;)
+ (NSArray<NSNumber *> * _Nonnull)blank SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithAppGroupId:(NSString * _Nonnull)appGroupId OBJC_DESIGNATED_INITIALIZER;
- (NSMutableData * _Nonnull)fixedInputData SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)tpyrcneWithPlaintext:(NSData * _Nonnull)plaintext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSMutableData * _Nullable)tpyrcedWithCiphertext:(NSData * _Nonnull)ciphertext error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)wipe;
- (void)reset;
- (SecKeyRef _Nullable)generateKskKeyPairAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (LAContext * _Nullable)generateContextAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDwp SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)applicationID SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6D1Core21KdfFeedbackHmacSha256")
@interface KdfFeedbackHmacSha256 : NSObject
@property (nonatomic) uint32_t keyLength;
@property (nonatomic, strong) NSMutableData * _Nonnull keyInput;
@property (nonatomic, strong) NSMutableData * _Nonnull iv;
@property (nonatomic, strong) NSMutableData * _Nonnull fixedInputData;
- (nonnull instancetype)initWithLength:(uint32_t)length input:(NSMutableData * _Nonnull)input iv:(NSMutableData * _Nonnull)iv fixedInputData:(NSMutableData * _Nonnull)fixedInputData OBJC_DESIGNATED_INITIALIZER;
- (NSMutableData * _Nullable)deriveAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)wipe;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, LogSubsystem, open) {
  LogSubsystemD1core = 0x00,
  LogSubsystemD1sdk = 0x01,
  LogSubsystemUnidentify = 0xFF,
};


SWIFT_CLASS("_TtC6D1Core6Memory")
@interface Memory : NSObject
+ (BOOL)validate:(NSMutableData * _Nonnull)data length:(NSInteger)length SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)memcmpWithData:(NSMutableData * _Nonnull)data otherData:(NSMutableData * _Nonnull)otherData length:(NSInteger)length SWIFT_WARN_UNUSED_RESULT;
+ (void)revxor:(NSMutableData * _Nonnull)dst src:(NSData * _Nonnull)src msk:(NSData * _Nonnull)msk;
+ (void)xor:(NSMutableData * _Nonnull)dst src:(NSMutableData * _Nonnull)src msk:(NSMutableData * _Nonnull)msk;
+ (void)shouldChangeCharactersInRangeWithCurrentMask:(NSMutableData * _Nonnull)currentMask currentInputValueMasked:(NSMutableData * _Nonnull)currentInputValueMasked tempMask:(NSMutableData * _Nonnull)tempMask nextInputValueMasked:(NSMutableData * _Nonnull)nextInputValueMasked newInputLength:(NSInteger)newInputLength rangeLoc:(NSInteger)rangeLoc rangeLen:(NSInteger)rangeLen stringLength:(NSInteger)stringLength fixedByteLength:(NSInteger)fixedByteLength subCharSequenceToChangeAfterChange:(NSMutableData * _Nonnull)subCharSequenceToChangeAfterChange;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core17MessagingEnumUtil")
@interface MessagingEnumUtil : NSObject
+ (D1CMessageType)messageTypeForString:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
+ (D1CMessageFormat)messageFormatForString:(NSString * _Nonnull)str SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core16MessagingStorage")
@interface MessagingStorage : EncryptedSqliteStorage
- (nullable instancetype)initWithConsumerId:(NSString * _Nullable)consumerId issuerId:(NSString * _Nullable)issuerId error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setShouldTryAfterLogin:(BOOL)tryUpdate error:(NSError * _Nullable * _Nullable)error;
- (BOOL)getShouldTryAfterLogin SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setIsRegistered:(BOOL)tokenRegistered error:(NSError * _Nullable * _Nullable)error;
- (BOOL)getIsRegistered SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core17NetworkMonitoring")
@interface NetworkMonitoring : NSObject
@property (nonatomic) BOOL isNetworkAvailable;
@property (nonatomic, readonly) BOOL isMonitoring;
@property (nonatomic, copy) void (^ _Nullable onUpdateNetworkStatus)(BOOL);
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NetworkMonitoring * _Nonnull shared;)
+ (NetworkMonitoring * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)startMonitoring;
- (void)stopMonitoring;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6D1Core33NotifyEnrollmentCompletionNetwork")
@interface NotifyEnrollmentCompletionNetwork : URLNetwork
@end


SWIFT_CLASS("_TtC6D1Core11PushStorage")
@interface PushStorage : EncryptedSqliteStorage
- (nullable instancetype)initAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)setPushToken:(NSString * _Nonnull)token error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getPushToken SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (nullable instancetype)initWithName:(NSString * _Nonnull)name appGroupId:(NSString * _Nullable)appGroupId error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6D1Core10RandomUtil")
@interface RandomUtil : NSObject
- (NSMutableData * _Nullable)randomDataWithCount:(NSInteger)count error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLAuthenticationChallenge;
@class NSURLCredential;

SWIFT_CLASS("_TtC6D1Core14SessionManager")
@interface SessionManager : NSObject <NSURLSessionTaskDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SessionManager * _Nonnull shared;)
+ (SessionManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <SessionManagerDelegate> _Nullable delegate;
@property (nonatomic, strong) NSURLSession * _Nullable session;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
@end






SWIFT_CLASS("_TtC6D1Core31UnenrollAuthnCredentialsNetwork")
@interface UnenrollAuthnCredentialsNetwork : URLNetwork
@end


SWIFT_CLASS("_TtC6D1Core5Wiper")
@interface Wiper : NSObject
+ (void)wipeBytes:(void const * _Nonnull)data length:(NSInteger)length;
+ (void)wipeData:(NSMutableData * _Nullable)data;
+ (void)wipeDataArray:(NSArray<NSData *> * _Nonnull)dataArray;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
